[phases.setup]
nixPkgs = ["...", "nodejs_20", "php83", "php83Packages.composer"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
